### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by random-robbie** [caffix/amass#9]
Go Lang 1.10 x64

ubuntu 16.04  x64

VPS: Vultr $5 1GB ram 

command

```
amass -vv -brute -o sb.txt starbucks.com
```

result:
```
goroutine 14692 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc43aaa6000                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13787 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439857960                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 14693 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc43aaa6070                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 14684 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc43aa67c70                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13800 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439857f10                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13770 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc4398571f0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13769 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439857180                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13768 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439857110                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13767 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc4398570a0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13766 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439857030                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13765 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856fc0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13764 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856f50                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13763 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856ee0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13762 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856e70                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13761 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856e00                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13760 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856d90                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13759 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856d20                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13758 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856cb0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13757 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856c40                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13756 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856bd0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13755 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856b60                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13754 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856af0                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13753 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856a80                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d

goroutine 13752 [chan send]:
github.com/caffix/amass/amass.(*SweepService).sendOut(0xc4202380a0, 0xc439856a10                                                                                                                                                             )
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:42 +0x58
created by github.com/caffix/amass/amass.(*SweepService).AttemptSweep
        /root/GO/src/github.com/caffix/amass/amass/sweep.go:78 +0x25d
```

**Comment by caffix** [comment]
Thanks for the feedback. I have discovered the problem, fixed it, and will be performing a commit soon.
